chore: comment task

diff --git a/.github/workflows/dispatch.yaml b/.github/workflows/dispatch.yaml
--- a/.github/workflows/dispatch.yaml
+++ b/.github/workflows/dispatch.yaml
@@ -57,28 +57,28 @@ jobs:
             | jq ".workflows[] | select(.name==\"$WORKFLOW_NAME\") | .id")
           echo "workflow_id=$ID" >> $GITHUB_OUTPUT
 
-      - name: Dispatch workflows per cluster
-        if: steps.detect.outputs.clusters != ''
-        run: |
-          IFS=' ' read -r -a clusters <<< "${{ steps.detect.outputs.clusters }}"
-          WORKFLOW_ID="${{ steps.workflow-id.outputs.workflow_id }}"
-          BRANCH="${GITHUB_HEAD_REF:-main}"
-          echo $WORKFLOW_ID
-          echo $BRANCH
-          for cluster in "${clusters[@]}"; do
-            echo "Dispatching deploy for cluster: $cluster"
-            RESPONSE=$(curl -L \
-              -X POST \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${{ secrets.TRIGGER_WORKFLOW_TOKEN }}" \
-              https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/dispatches \
-              -d "{\"ref\":\"$BRANCH\",\"inputs\":{\"cluster\":\"$cluster\"}}" \
-              -w "%{http_code}" -o /dev/null)
-            if [ "$RESPONSE" -ne 204 ]; then
-              echo "Error: Failed to dispatch workflow for cluster: $cluster (HTTP status: $RESPONSE)"
-              exit 1
-            fi
-          done
+      # - name: Dispatch workflows per cluster
+      #   if: steps.detect.outputs.clusters != ''
+      #   run: |
+      #     IFS=' ' read -r -a clusters <<< "${{ steps.detect.outputs.clusters }}"
+      #     WORKFLOW_ID="${{ steps.workflow-id.outputs.workflow_id }}"
+      #     BRANCH="${GITHUB_HEAD_REF:-main}"
+      #     echo $WORKFLOW_ID
+      #     echo $BRANCH
+      #     for cluster in "${clusters[@]}"; do
+      #       echo "Dispatching deploy for cluster: $cluster"
+      #       RESPONSE=$(curl -L \
+      #         -X POST \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "Authorization: Bearer ${{ secrets.TRIGGER_WORKFLOW_TOKEN }}" \
+      #         https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/dispatches \
+      #         -d "{\"ref\":\"$BRANCH\",\"inputs\":{\"cluster\":\"$cluster\"}}" \
+      #         -w "%{http_code}" -o /dev/null)
+      #       if [ "$RESPONSE" -ne 204 ]; then
+      #         echo "Error: Failed to dispatch workflow for cluster: $cluster (HTTP status: $RESPONSE)"
+      #         exit 1
+      #       fi
+      #     done
 
       - name: Dispatch workflows per cluster
         if: steps.detect.outputs.clusters != ''
